name: portfolio_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  equatable: ^2.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
