name: portfolio_ui
description: "A Flutter package that contains UI components and design system for NACD."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # For UI and styling:
  mix: ^1.5.4
  gap: ^3.0.1
  google_fonts: ^6.2.1

  # Utils:
  intl: ^0.19.0
  fluttertoast: ^8.2.12

  # For images and icons:
  vector_graphics: ^1.1.18
  cached_network_image: ^3.4.1
  transparent_image: ^2.0.1
  portfolio_core:
    path: ../portfolio_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
